export const premiumListings = [
  {
    id: "cathedral-c14",
    image: "/new files/new demo images/Demo 2_Main.jpg",
    thumbnailImages: [
      "/new files/new demo images/1.jpg",
      "/new files/new demo images/2.jpg",
      "/new files/new demo images/3.jpg",
      "/new files/new demo images/4.jpg",
      "/new files/new demo images/5.jpg",
      "/new files/new demo images/6.jpg",
      "/new files/new demo images/Demo 2_Main.jpg"
    ],
    price: "R 8 820",
    title: "CATHEDRAL C14",
    details: "Full Tombstone | Granite | Cross Theme",
    features: "Photo Engraving Available | Self Install & Pick-Up Available",
    manufacturer: "Example Tombstone Co.",
    enquiries: "21",
    location: "Durban North, KZN",
    distance: "38km from you",
    tag: "Unique Design",
    tagColor: "bg-red-600 hover:bg-red-700",
    tagRingColor: "red-400",
  },
  {
    id: "elegant-marble",
    image: "/X20Tombstone_Pic Sets/cross3/Cross2_Main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/cross3/Cross2_1.jpg",
      "/X20Tombstone_Pic Sets/cross3/Cross2_2.jpg",
      "/X20Tombstone_Pic Sets/cross3/Cross2_3.jpg"
    ],
    price: "R 12 450",
    title: "ELEGANT MARBLE MEMORIAL",
    details: "Full Tombstone | Marble | Angel Theme",
    features: "Gold Leaf Lettering Available | Delivery Included",
    manufacturer: "Marble Masters",
    enquiries: "15",
    location: "Cape Town, Western Cape",
    distance: "120km from you",
    tag: "Premium Quality",
    tagColor: "bg-blue-600 hover:bg-blue-700",
    tagRingColor: "blue-400",
  },
  {
    id: "black-granite",
    image: "/X20Tombstone_Pic Sets/mausoleam/mausoleam_main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/mausoleam/mausoleam_1.jpg",
      "/X20Tombstone_Pic Sets/mausoleam/mausoleam_2.jpg",
      "/X20Tombstone_Pic Sets/mausoleam/mausoleam_3.jpg"
    ],
    price: "R 15 750",
    title: "BLACK GRANITE MEMORIAL",
    details: "Full Tombstone | Black Granite | Modern Theme",
    features: "Laser Engraving | 5-Year Warranty",
    manufacturer: "Granite Specialists",
    enquiries: "32",
    location: "Johannesburg, Gauteng",
    distance: "25km from you",
    tag: "Best Seller",
    tagColor: "bg-purple-600 hover:bg-purple-700",
    tagRingColor: "purple-400",
  },
  {
    id: "traditional-double",
    image: "/X20Tombstone_Pic Sets/mausoleam2/Mausoleam2_Main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/mausoleam2/Mausoleam2_1.jpg",
      "/X20Tombstone_Pic Sets/mausoleam2/Mausoleam2_2.jpg",
      "/X20Tombstone_Pic Sets/mausoleam2/Mausoleam2_Main.jpg"
    ],
    price: "R 22 980",
    title: "TRADITIONAL DOUBLE HEADSTONE",
    details: "Double Tombstone | Granite | Traditional Theme",
    features: "Dual Inscription | Installation Included",
    manufacturer: "Family Memorials Ltd",
    enquiries: "18",
    location: "Bloemfontein, Free State",
    distance: "210km from you",
    tag: "Family Option",
    tagColor: "bg-green-600 hover:bg-green-700",
    tagRingColor: "green-400",
  },
  {
    id: "cultural-heritage",
    image: "/X20Tombstone_Pic Sets/bigbible_mainPIc/BigBible_Main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/bigbible_mainPIc/BigBible_Main.jpg",
      "/X20Tombstone_Pic Sets/bigbible_mainPIc/BigBible_Main.jpg",
      "/X20Tombstone_Pic Sets/bigbible_mainPIc/BigBible_Main.jpg"
    ],
    price: "R 18 350",
    title: "CULTURAL HERITAGE MEMORIAL",
    details: "Full Tombstone | Granite & Bronze | Cultural Theme",
    features: "Custom Cultural Symbols | Multilingual Inscriptions",
    manufacturer: "Heritage Memorials",
    enquiries: "24",
    location: "Pretoria, Gauteng",
    distance: "45km from you",
    tag: "Cultural Design",
    tagColor: "bg-amber-600 hover:bg-amber-700",
    tagRingColor: "amber-400",
  },
  {
    id: "modern-abstract",
    image: "/X20Tombstone_Pic Sets/Abstract/Abstract_Main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/Abstract/Abstract_1.jpg",
      "/X20Tombstone_Pic Sets/Abstract/Abstract_2.jpg",
      "/X20Tombstone_Pic Sets/Abstract/Abstract_3.jpg"
    ],
    price: "R 21 000",
    title: "MODERN ABSTRACT SCULPTURE",
    details: "Sculpture | Granite | Abstract Theme",
    features: "Unique Shape | Artistic Design | Custom Engraving",
    manufacturer: "Artful Memorials",
    enquiries: "19",
    location: "Cape Town, Western Cape",
    distance: "110km from you",
    tag: "Artistic",
    tagColor: "bg-teal-600 hover:bg-teal-700",
    tagRingColor: "teal-400",
  },
  {
    id: "garden-style-marker",
    image: "/X20Tombstone_Pic Sets/stepped/Stepped_Main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/stepped/Stepped_1.jpg",
      "/X20Tombstone_Pic Sets/stepped/Stepped_2.jpg",
      "/X20Tombstone_Pic Sets/stepped/Stepped_Main.jpg"
    ],
    price: "R 7 500",
    title: "GARDEN STYLE FLAT MARKER",
    details: "Flat Marker | Bronze | Nature Theme",
    features: "Integrated Vase | Low Profile | Durable Bronze",
    manufacturer: "Bronze Crafters",
    enquiries: "14",
    location: "Durban, KZN",
    distance: "60km from you",
    tag: "Garden Accent",
    tagColor: "bg-yellow-600 hover:bg-yellow-700",
    tagRingColor: "yellow-400",
  },
  {
    id: "religious-themed-upright",
    image: "/X20Tombstone_Pic Sets/cross1/Cross_Main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/cross1/Cross_1.jpg",
      "/X20Tombstone_Pic Sets/cross1/Cross_2.jpg",
      "/X20Tombstone_Pic Sets/cross1/Cross_Main.jpg"
    ],
    price: "R 16 500",
    title: "RELIGIOUS THEMED UPRIGHT",
    details: "Upright Tombstone | Granite | Religious Theme",
    features: "Cross/Star of David/Crescent Symbol | Custom Verses",
    manufacturer: "Sacred Stones",
    enquiries: "35",
    location: "Johannesburg, Gauteng",
    distance: "20km from you",
    tag: "Faith Inspired",
    tagColor: "bg-orange-600 hover:bg-orange-700",
    tagRingColor: "orange-400",
  },
  {
    id: "companion-bench-memorial",
    image: "/X20Tombstone_Pic Sets/mausoleam3/mausoleam3_main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/mausoleam3/mausoleam3_1.jpg",
      "/X20Tombstone_Pic Sets/mausoleam3/mausoleam3_2.jpg",
      "/X20Tombstone_Pic Sets/mausoleam3/mausoleam3_main.jpg"
    ],
    price: "R 25 000",
    title: "COMPANION BENCH MEMORIAL",
    details: "Bench Memorial | Granite | Shared Theme",
    features: "Seating Area | Double Inscription | Durable",
    manufacturer: "Comforting Creations",
    enquiries: "22",
    location: "Pretoria, Gauteng",
    distance: "55km from you",
    tag: "Shared Memory",
    tagColor: "bg-brown-600 hover:bg-brown-700",
    tagRingColor: "brown-400",
  },
  {
    id: "unique-child-design",
    image: "/X20Tombstone_Pic Sets/child/Child_Main.jpg",
    thumbnailImages: [
      "/X20Tombstone_Pic Sets/child/Child_1.jpg",
      "/X20Tombstone_Pic Sets/child/Child_2.jpg",
      "/X20Tombstone_Pic Sets/child/Child_Main.jpg"
    ],
    price: "R 8 000",
    title: "UNIQUE CHILD MEMORIAL DESIGN",
    details: "Child Memorial | Marble | Custom Design",
    features: "Personalized Artwork | Smaller Scale",
    manufacturer: "Little Angels Memorials",
    enquiries: "9",
    location: "Bloemfontein, Free State",
    distance: "220km from you",
    tag: "Personalized",
    tagColor: "bg-pink-400 hover:bg-pink-500",
    tagRingColor: "pink-200",
  },
]; 

export const manufacturerProducts = [
  {
    id: "manufacturer-1",
    image: "/X20Tombstone_Pic Sets/cross1/Cross_Main.jpg",
    price: "R 10 200",
    title: "WHITE CROSS",
    details: "Full Tombstone | Granite | Cross Theme",
    manufacturer: "ABC Tombstones PTY Ltd",
    location: "Johannesburg, Gauteng"
  },
  {
    id: "manufacturer-2",
    image: "/X20Tombstone_Pic Sets/bible/Bible_Main.jpg",
    price: "R 28 500",
    title: "WHITE ANGEL",
    details: "Full Tombstone | Granite | Bible Theme",
    manufacturer: "ABC Tombstones PTY Ltd",
    location: "Johannesburg, Gauteng"
  },
  {
    id: "manufacturer-3",
    image: "/X20Tombstone_Pic Sets/cross2/Cross2_Main.jpg",
    price: "R 19 900",
    title: "GOLD CROSS",
    details: "Full Tombstone | Marble | Cross Theme",
    manufacturer: "ABC Tombstones PTY Ltd",
    location: "Johannesburg, Gauteng"
  }
];

export const standardListings = [
  {
    id: "standard-1",
    image: "/X20Tombstone_Pic Sets/cross1/Cross_Main.jpg",
    price: "R 8 500",
    title: "CLASSIC CROSS",
    details: "Full Tombstone | Granite | Cross Theme",
    manufacturer: "Standard Memorials",
    location: "Pretoria, Gauteng"
  },
  {
    id: "standard-2",
    image: "/X20Tombstone_Pic Sets/bible/Bible_Main.jpg",
    price: "R 12 000",
    title: "TRADITIONAL BIBLE",
    details: "Full Tombstone | Granite | Bible Theme",
    manufacturer: "Standard Memorials",
    location: "Pretoria, Gauteng"
  },
  {
    id: "standard-3",
    image: "/X20Tombstone_Pic Sets/cross2/Cross2_Main.jpg",
    price: "R 15 000",
    title: "MODERN CROSS",
    details: "Full Tombstone | Marble | Cross Theme",
    manufacturer: "Standard Memorials",
    location: "Pretoria, Gauteng"
  }
]; 