// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/blogs" | "/blogs/[slug]" | "/locations/[...segments]" | "/manufacturers/[slug]" | "/tombstones/[slug]"
type AppRouteHandlerRoutes = "/api/auth/[...nextauth]" | "/api/blog-posts/[documentId]" | "/api/branches/[documentId]" | "/api/cloudinary/delete" | "/api/companies/[documentId]/listings" | "/api/company-special-offer-visibility" | "/api/distance" | "/api/filter-visibility" | "/api/inquiries/[id]/mark-read" | "/api/listing-categories/[documentId]" | "/api/listings/[documentId]" | "/api/local-businesses" | "/api/local-businesses/[documentId]" | "/api/location-landing-seos" | "/api/location-landing-seos/[documentId]" | "/api/maintenance-mode" | "/api/page-visibility" | "/api/upload/cloudinary" | "/robots.txt"
type PageRoutes = "/_document"
type LayoutRoutes = "/" | "/blogs" | "/contact" | "/manufacturers" | "/services" | "/tombstones-for-sale" | "/tombstones-on-special" | "/tombstones-on-special/[id]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/_document": {}
  "/api/auth/[...nextauth]": { "nextauth": string[]; }
  "/api/blog-posts/[documentId]": { "documentId": string; }
  "/api/branches/[documentId]": { "documentId": string; }
  "/api/cloudinary/delete": {}
  "/api/companies/[documentId]/listings": { "documentId": string; }
  "/api/company-special-offer-visibility": {}
  "/api/distance": {}
  "/api/filter-visibility": {}
  "/api/inquiries/[id]/mark-read": { "id": string; }
  "/api/listing-categories/[documentId]": { "documentId": string; }
  "/api/listings/[documentId]": { "documentId": string; }
  "/api/local-businesses": {}
  "/api/local-businesses/[documentId]": { "documentId": string; }
  "/api/location-landing-seos": {}
  "/api/location-landing-seos/[documentId]": { "documentId": string; }
  "/api/maintenance-mode": {}
  "/api/page-visibility": {}
  "/api/upload/cloudinary": {}
  "/blogs": {}
  "/blogs/[slug]": { "slug": string; }
  "/contact": {}
  "/locations/[...segments]": { "segments": string[]; }
  "/manufacturers": {}
  "/manufacturers/[slug]": { "slug": string; }
  "/robots.txt": {}
  "/services": {}
  "/tombstones-for-sale": {}
  "/tombstones-on-special": {}
  "/tombstones-on-special/[id]": { "id": string; }
  "/tombstones/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/blogs": never
  "/contact": never
  "/manufacturers": never
  "/services": never
  "/tombstones-for-sale": never
  "/tombstones-on-special": never
  "/tombstones-on-special/[id]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
