// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/blogs/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blogs/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blogs/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blogs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blogs">> = Specific
  const handler = {} as typeof import("../../app/blogs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/locations/[...segments]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/locations/[...segments]">> = Specific
  const handler = {} as typeof import("../../app/locations/[...segments]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manufacturers/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/manufacturers/[slug]">> = Specific
  const handler = {} as typeof import("../../app/manufacturers/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tombstones/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tombstones/[slug]">> = Specific
  const handler = {} as typeof import("../../app/tombstones/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/company-special-offer-visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/company-special-offer-visibility">> = Specific
  const handler = {} as typeof import("../../app/api/company-special-offer-visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/filter-visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/filter-visibility">> = Specific
  const handler = {} as typeof import("../../app/api/filter-visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance-mode/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance-mode">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance-mode/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/page-visibility/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/page-visibility">> = Specific
  const handler = {} as typeof import("../../app/api/page-visibility/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/robots.txt/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/robots.txt">> = Specific
  const handler = {} as typeof import("../../app/robots.txt/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/blogs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/blogs">> = Specific
  const handler = {} as typeof import("../../app/blogs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/manufacturers/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/manufacturers">> = Specific
  const handler = {} as typeof import("../../app/manufacturers/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tombstones-for-sale/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tombstones-for-sale">> = Specific
  const handler = {} as typeof import("../../app/tombstones-for-sale/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tombstones-on-special/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/tombstones-on-special/[id]">> = Specific
  const handler = {} as typeof import("../../app/tombstones-on-special/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
